server-ip=127.0.0.1
server-port=25566
online-mode=false
enforce-secure-profile=false
enable-rcon=false
enable-query=false
level-name=arena
level-type=minecraft:flat
generator-settings={"layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":62},{"block":"minecraft:grass_block","height":1}],"biome":"minecraft:plains","features":false,"lakes":false,"structure_overrides":[]}
generate-structures=false
gamemode=survival
difficulty=normal
pvp=true
max-players=128
view-distance=2
simulation-distance=2
allow-flight=true
spawn-protection=0
motd=NBMCBot local PvP arena
